### ISSUE TITLE
Linux build

### ISSUE THREAD

**Issue by Jogai** [DaGooseYT/EncodeGUI#10]
Would you consider compiling for linux? Since its qt based already...

**Comment by DaGooseYT** [comment]
EncodeGUI for Linux was supposed to be released a few months ago but was halted due to compilation issues. 
While it's true that Qt apps can be easily compiled on other OSs, it's not the case with EncodeGUI. Many changes will have to be made internally including the methods to detect GPUs, suspending processes, and finding CPU information. Furthermore, all of the dependencies will have to be compiled for Linux and a new corresponding setup installer wizard will have to be made. 
Regardless, it's still a possibility, but if so we won't see a Linux build for a while because there isn't a large demand for it currently.
